use_modular_headers!

def shared_pods
  #use_frameworks!

  pod 'Alamofire', '~> 4.5.0'
  pod 'Cashier', '~> 1.2.1', :modular_headers => true
  pod 'Serpent', '~> 1.1.0'
end

target 'NStackSDK' do
  platform :ios, '9.0'

  shared_pods

end

target 'NStackSDK-macOS' do
  platform :osx, '10.10'

  shared_pods

end

target 'NStackSDK-tvOS' do
  platform :tvos, '9.0'

  shared_pods

end

target 'NStackSDK-watchOS' do
  platform :watchos, '2.0'

  shared_pods

end


